# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/austin/cxl_transaction/cicada_CXLtransaction

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/austin/cxl_transaction/cicada_CXLtransaction

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/austin/cxl_transaction/cicada_CXLtransaction/CMakeFiles /home/austin/cxl_transaction/cicada_CXLtransaction/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/austin/cxl_transaction/cicada_CXLtransaction/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named test_tx

# Build rule for target.
test_tx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tx
.PHONY : test_tx

# fast build rule for target.
test_tx/fast:
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/build
.PHONY : test_tx/fast

#=============================================================================
# Target rules for targets named test_tx_index

# Build rule for target.
test_tx_index: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tx_index
.PHONY : test_tx_index

# fast build rule for target.
test_tx_index/fast:
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/build
.PHONY : test_tx_index/fast

#=============================================================================
# Target rules for targets named test_partial_commit

# Build rule for target.
test_partial_commit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_partial_commit
.PHONY : test_partial_commit

# fast build rule for target.
test_partial_commit/fast:
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/build
.PHONY : test_partial_commit/fast

#=============================================================================
# Target rules for targets named test_cxl_detection

# Build rule for target.
test_cxl_detection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cxl_detection
.PHONY : test_cxl_detection

# fast build rule for target.
test_cxl_detection/fast:
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/build
.PHONY : test_cxl_detection/fast

#=============================================================================
# Target rules for targets named test_cxl_slot

# Build rule for target.
test_cxl_slot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cxl_slot
.PHONY : test_cxl_slot

# fast build rule for target.
test_cxl_slot/fast:
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/build
.PHONY : test_cxl_slot/fast

#=============================================================================
# Target rules for targets named test_tsc_sync

# Build rule for target.
test_tsc_sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tsc_sync
.PHONY : test_tsc_sync

# fast build rule for target.
test_tsc_sync/fast:
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/build
.PHONY : test_tsc_sync/fast

#=============================================================================
# Target rules for targets named test_bwtree_index

# Build rule for target.
test_bwtree_index: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bwtree_index
.PHONY : test_bwtree_index

# fast build rule for target.
test_bwtree_index/fast:
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/build
.PHONY : test_bwtree_index/fast

#=============================================================================
# Target rules for targets named test_atomics

# Build rule for target.
test_atomics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_atomics
.PHONY : test_atomics

# fast build rule for target.
test_atomics/fast:
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/build
.PHONY : test_atomics/fast

#=============================================================================
# Target rules for targets named test_cxl_row_data

# Build rule for target.
test_cxl_row_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cxl_row_data
.PHONY : test_cxl_row_data

# fast build rule for target.
test_cxl_row_data/fast:
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/build
.PHONY : test_cxl_row_data/fast

#=============================================================================
# Target rules for targets named test_simple_slot_read

# Build rule for target.
test_simple_slot_read: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_simple_slot_read
.PHONY : test_simple_slot_read

# fast build rule for target.
test_simple_slot_read/fast:
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/build
.PHONY : test_simple_slot_read/fast

#=============================================================================
# Target rules for targets named test_commit_slot_access

# Build rule for target.
test_commit_slot_access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_commit_slot_access
.PHONY : test_commit_slot_access

# fast build rule for target.
test_commit_slot_access/fast:
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/build
.PHONY : test_commit_slot_access/fast

src/mica/alloc/hugetlbfs_shm.o: src/mica/alloc/hugetlbfs_shm.cc.o

.PHONY : src/mica/alloc/hugetlbfs_shm.o

# target to build an object file
src/mica/alloc/hugetlbfs_shm.cc.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/alloc/hugetlbfs_shm.cc.o
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/alloc/hugetlbfs_shm.cc.o
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/alloc/hugetlbfs_shm.cc.o
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/alloc/hugetlbfs_shm.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/alloc/hugetlbfs_shm.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/alloc/hugetlbfs_shm.cc.o
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/alloc/hugetlbfs_shm.cc.o
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/alloc/hugetlbfs_shm.cc.o
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/alloc/hugetlbfs_shm.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/alloc/hugetlbfs_shm.cc.o
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/alloc/hugetlbfs_shm.cc.o
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/alloc/hugetlbfs_shm.cc.o
.PHONY : src/mica/alloc/hugetlbfs_shm.cc.o

src/mica/alloc/hugetlbfs_shm.i: src/mica/alloc/hugetlbfs_shm.cc.i

.PHONY : src/mica/alloc/hugetlbfs_shm.i

# target to preprocess a source file
src/mica/alloc/hugetlbfs_shm.cc.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/alloc/hugetlbfs_shm.cc.i
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/alloc/hugetlbfs_shm.cc.i
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/alloc/hugetlbfs_shm.cc.i
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/alloc/hugetlbfs_shm.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/alloc/hugetlbfs_shm.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/alloc/hugetlbfs_shm.cc.i
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/alloc/hugetlbfs_shm.cc.i
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/alloc/hugetlbfs_shm.cc.i
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/alloc/hugetlbfs_shm.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/alloc/hugetlbfs_shm.cc.i
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/alloc/hugetlbfs_shm.cc.i
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/alloc/hugetlbfs_shm.cc.i
.PHONY : src/mica/alloc/hugetlbfs_shm.cc.i

src/mica/alloc/hugetlbfs_shm.s: src/mica/alloc/hugetlbfs_shm.cc.s

.PHONY : src/mica/alloc/hugetlbfs_shm.s

# target to generate assembly for a file
src/mica/alloc/hugetlbfs_shm.cc.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/alloc/hugetlbfs_shm.cc.s
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/alloc/hugetlbfs_shm.cc.s
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/alloc/hugetlbfs_shm.cc.s
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/alloc/hugetlbfs_shm.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/alloc/hugetlbfs_shm.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/alloc/hugetlbfs_shm.cc.s
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/alloc/hugetlbfs_shm.cc.s
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/alloc/hugetlbfs_shm.cc.s
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/alloc/hugetlbfs_shm.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/alloc/hugetlbfs_shm.cc.s
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/alloc/hugetlbfs_shm.cc.s
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/alloc/hugetlbfs_shm.cc.s
.PHONY : src/mica/alloc/hugetlbfs_shm.cc.s

src/mica/test/test_atomics.o: src/mica/test/test_atomics.cc.o

.PHONY : src/mica/test/test_atomics.o

# target to build an object file
src/mica/test/test_atomics.cc.o:
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/test/test_atomics.cc.o
.PHONY : src/mica/test/test_atomics.cc.o

src/mica/test/test_atomics.i: src/mica/test/test_atomics.cc.i

.PHONY : src/mica/test/test_atomics.i

# target to preprocess a source file
src/mica/test/test_atomics.cc.i:
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/test/test_atomics.cc.i
.PHONY : src/mica/test/test_atomics.cc.i

src/mica/test/test_atomics.s: src/mica/test/test_atomics.cc.s

.PHONY : src/mica/test/test_atomics.s

# target to generate assembly for a file
src/mica/test/test_atomics.cc.s:
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/test/test_atomics.cc.s
.PHONY : src/mica/test/test_atomics.cc.s

src/mica/test/test_bwtree_index.o: src/mica/test/test_bwtree_index.cc.o

.PHONY : src/mica/test/test_bwtree_index.o

# target to build an object file
src/mica/test/test_bwtree_index.cc.o:
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/test/test_bwtree_index.cc.o
.PHONY : src/mica/test/test_bwtree_index.cc.o

src/mica/test/test_bwtree_index.i: src/mica/test/test_bwtree_index.cc.i

.PHONY : src/mica/test/test_bwtree_index.i

# target to preprocess a source file
src/mica/test/test_bwtree_index.cc.i:
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/test/test_bwtree_index.cc.i
.PHONY : src/mica/test/test_bwtree_index.cc.i

src/mica/test/test_bwtree_index.s: src/mica/test/test_bwtree_index.cc.s

.PHONY : src/mica/test/test_bwtree_index.s

# target to generate assembly for a file
src/mica/test/test_bwtree_index.cc.s:
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/test/test_bwtree_index.cc.s
.PHONY : src/mica/test/test_bwtree_index.cc.s

src/mica/test/test_commit_slot_access.o: src/mica/test/test_commit_slot_access.cc.o

.PHONY : src/mica/test/test_commit_slot_access.o

# target to build an object file
src/mica/test/test_commit_slot_access.cc.o:
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/test/test_commit_slot_access.cc.o
.PHONY : src/mica/test/test_commit_slot_access.cc.o

src/mica/test/test_commit_slot_access.i: src/mica/test/test_commit_slot_access.cc.i

.PHONY : src/mica/test/test_commit_slot_access.i

# target to preprocess a source file
src/mica/test/test_commit_slot_access.cc.i:
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/test/test_commit_slot_access.cc.i
.PHONY : src/mica/test/test_commit_slot_access.cc.i

src/mica/test/test_commit_slot_access.s: src/mica/test/test_commit_slot_access.cc.s

.PHONY : src/mica/test/test_commit_slot_access.s

# target to generate assembly for a file
src/mica/test/test_commit_slot_access.cc.s:
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/test/test_commit_slot_access.cc.s
.PHONY : src/mica/test/test_commit_slot_access.cc.s

src/mica/test/test_cxl_detection.o: src/mica/test/test_cxl_detection.cc.o

.PHONY : src/mica/test/test_cxl_detection.o

# target to build an object file
src/mica/test/test_cxl_detection.cc.o:
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/test/test_cxl_detection.cc.o
.PHONY : src/mica/test/test_cxl_detection.cc.o

src/mica/test/test_cxl_detection.i: src/mica/test/test_cxl_detection.cc.i

.PHONY : src/mica/test/test_cxl_detection.i

# target to preprocess a source file
src/mica/test/test_cxl_detection.cc.i:
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/test/test_cxl_detection.cc.i
.PHONY : src/mica/test/test_cxl_detection.cc.i

src/mica/test/test_cxl_detection.s: src/mica/test/test_cxl_detection.cc.s

.PHONY : src/mica/test/test_cxl_detection.s

# target to generate assembly for a file
src/mica/test/test_cxl_detection.cc.s:
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/test/test_cxl_detection.cc.s
.PHONY : src/mica/test/test_cxl_detection.cc.s

src/mica/test/test_cxl_row_data.o: src/mica/test/test_cxl_row_data.cc.o

.PHONY : src/mica/test/test_cxl_row_data.o

# target to build an object file
src/mica/test/test_cxl_row_data.cc.o:
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/test/test_cxl_row_data.cc.o
.PHONY : src/mica/test/test_cxl_row_data.cc.o

src/mica/test/test_cxl_row_data.i: src/mica/test/test_cxl_row_data.cc.i

.PHONY : src/mica/test/test_cxl_row_data.i

# target to preprocess a source file
src/mica/test/test_cxl_row_data.cc.i:
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/test/test_cxl_row_data.cc.i
.PHONY : src/mica/test/test_cxl_row_data.cc.i

src/mica/test/test_cxl_row_data.s: src/mica/test/test_cxl_row_data.cc.s

.PHONY : src/mica/test/test_cxl_row_data.s

# target to generate assembly for a file
src/mica/test/test_cxl_row_data.cc.s:
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/test/test_cxl_row_data.cc.s
.PHONY : src/mica/test/test_cxl_row_data.cc.s

src/mica/test/test_cxl_slot.o: src/mica/test/test_cxl_slot.cc.o

.PHONY : src/mica/test/test_cxl_slot.o

# target to build an object file
src/mica/test/test_cxl_slot.cc.o:
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/test/test_cxl_slot.cc.o
.PHONY : src/mica/test/test_cxl_slot.cc.o

src/mica/test/test_cxl_slot.i: src/mica/test/test_cxl_slot.cc.i

.PHONY : src/mica/test/test_cxl_slot.i

# target to preprocess a source file
src/mica/test/test_cxl_slot.cc.i:
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/test/test_cxl_slot.cc.i
.PHONY : src/mica/test/test_cxl_slot.cc.i

src/mica/test/test_cxl_slot.s: src/mica/test/test_cxl_slot.cc.s

.PHONY : src/mica/test/test_cxl_slot.s

# target to generate assembly for a file
src/mica/test/test_cxl_slot.cc.s:
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/test/test_cxl_slot.cc.s
.PHONY : src/mica/test/test_cxl_slot.cc.s

src/mica/test/test_partial_commit.o: src/mica/test/test_partial_commit.cc.o

.PHONY : src/mica/test/test_partial_commit.o

# target to build an object file
src/mica/test/test_partial_commit.cc.o:
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/test/test_partial_commit.cc.o
.PHONY : src/mica/test/test_partial_commit.cc.o

src/mica/test/test_partial_commit.i: src/mica/test/test_partial_commit.cc.i

.PHONY : src/mica/test/test_partial_commit.i

# target to preprocess a source file
src/mica/test/test_partial_commit.cc.i:
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/test/test_partial_commit.cc.i
.PHONY : src/mica/test/test_partial_commit.cc.i

src/mica/test/test_partial_commit.s: src/mica/test/test_partial_commit.cc.s

.PHONY : src/mica/test/test_partial_commit.s

# target to generate assembly for a file
src/mica/test/test_partial_commit.cc.s:
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/test/test_partial_commit.cc.s
.PHONY : src/mica/test/test_partial_commit.cc.s

src/mica/test/test_simple_slot_read.o: src/mica/test/test_simple_slot_read.cc.o

.PHONY : src/mica/test/test_simple_slot_read.o

# target to build an object file
src/mica/test/test_simple_slot_read.cc.o:
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/test/test_simple_slot_read.cc.o
.PHONY : src/mica/test/test_simple_slot_read.cc.o

src/mica/test/test_simple_slot_read.i: src/mica/test/test_simple_slot_read.cc.i

.PHONY : src/mica/test/test_simple_slot_read.i

# target to preprocess a source file
src/mica/test/test_simple_slot_read.cc.i:
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/test/test_simple_slot_read.cc.i
.PHONY : src/mica/test/test_simple_slot_read.cc.i

src/mica/test/test_simple_slot_read.s: src/mica/test/test_simple_slot_read.cc.s

.PHONY : src/mica/test/test_simple_slot_read.s

# target to generate assembly for a file
src/mica/test/test_simple_slot_read.cc.s:
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/test/test_simple_slot_read.cc.s
.PHONY : src/mica/test/test_simple_slot_read.cc.s

src/mica/test/test_tsc_sync.o: src/mica/test/test_tsc_sync.cc.o

.PHONY : src/mica/test/test_tsc_sync.o

# target to build an object file
src/mica/test/test_tsc_sync.cc.o:
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/test/test_tsc_sync.cc.o
.PHONY : src/mica/test/test_tsc_sync.cc.o

src/mica/test/test_tsc_sync.i: src/mica/test/test_tsc_sync.cc.i

.PHONY : src/mica/test/test_tsc_sync.i

# target to preprocess a source file
src/mica/test/test_tsc_sync.cc.i:
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/test/test_tsc_sync.cc.i
.PHONY : src/mica/test/test_tsc_sync.cc.i

src/mica/test/test_tsc_sync.s: src/mica/test/test_tsc_sync.cc.s

.PHONY : src/mica/test/test_tsc_sync.s

# target to generate assembly for a file
src/mica/test/test_tsc_sync.cc.s:
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/test/test_tsc_sync.cc.s
.PHONY : src/mica/test/test_tsc_sync.cc.s

src/mica/test/test_tx.o: src/mica/test/test_tx.cc.o

.PHONY : src/mica/test/test_tx.o

# target to build an object file
src/mica/test/test_tx.cc.o:
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/test/test_tx.cc.o
.PHONY : src/mica/test/test_tx.cc.o

src/mica/test/test_tx.i: src/mica/test/test_tx.cc.i

.PHONY : src/mica/test/test_tx.i

# target to preprocess a source file
src/mica/test/test_tx.cc.i:
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/test/test_tx.cc.i
.PHONY : src/mica/test/test_tx.cc.i

src/mica/test/test_tx.s: src/mica/test/test_tx.cc.s

.PHONY : src/mica/test/test_tx.s

# target to generate assembly for a file
src/mica/test/test_tx.cc.s:
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/test/test_tx.cc.s
.PHONY : src/mica/test/test_tx.cc.s

src/mica/test/test_tx_index.o: src/mica/test/test_tx_index.cc.o

.PHONY : src/mica/test/test_tx_index.o

# target to build an object file
src/mica/test/test_tx_index.cc.o:
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/test/test_tx_index.cc.o
.PHONY : src/mica/test/test_tx_index.cc.o

src/mica/test/test_tx_index.i: src/mica/test/test_tx_index.cc.i

.PHONY : src/mica/test/test_tx_index.i

# target to preprocess a source file
src/mica/test/test_tx_index.cc.i:
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/test/test_tx_index.cc.i
.PHONY : src/mica/test/test_tx_index.cc.i

src/mica/test/test_tx_index.s: src/mica/test/test_tx_index.cc.s

.PHONY : src/mica/test/test_tx_index.s

# target to generate assembly for a file
src/mica/test/test_tx_index.cc.s:
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/test/test_tx_index.cc.s
.PHONY : src/mica/test/test_tx_index.cc.s

src/mica/transaction/timestamp.o: src/mica/transaction/timestamp.cc.o

.PHONY : src/mica/transaction/timestamp.o

# target to build an object file
src/mica/transaction/timestamp.cc.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/transaction/timestamp.cc.o
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/transaction/timestamp.cc.o
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/transaction/timestamp.cc.o
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/transaction/timestamp.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/transaction/timestamp.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/transaction/timestamp.cc.o
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/transaction/timestamp.cc.o
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/transaction/timestamp.cc.o
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/transaction/timestamp.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/transaction/timestamp.cc.o
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/transaction/timestamp.cc.o
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/transaction/timestamp.cc.o
.PHONY : src/mica/transaction/timestamp.cc.o

src/mica/transaction/timestamp.i: src/mica/transaction/timestamp.cc.i

.PHONY : src/mica/transaction/timestamp.i

# target to preprocess a source file
src/mica/transaction/timestamp.cc.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/transaction/timestamp.cc.i
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/transaction/timestamp.cc.i
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/transaction/timestamp.cc.i
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/transaction/timestamp.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/transaction/timestamp.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/transaction/timestamp.cc.i
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/transaction/timestamp.cc.i
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/transaction/timestamp.cc.i
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/transaction/timestamp.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/transaction/timestamp.cc.i
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/transaction/timestamp.cc.i
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/transaction/timestamp.cc.i
.PHONY : src/mica/transaction/timestamp.cc.i

src/mica/transaction/timestamp.s: src/mica/transaction/timestamp.cc.s

.PHONY : src/mica/transaction/timestamp.s

# target to generate assembly for a file
src/mica/transaction/timestamp.cc.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/transaction/timestamp.cc.s
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/transaction/timestamp.cc.s
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/transaction/timestamp.cc.s
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/transaction/timestamp.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/transaction/timestamp.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/transaction/timestamp.cc.s
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/transaction/timestamp.cc.s
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/transaction/timestamp.cc.s
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/transaction/timestamp.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/transaction/timestamp.cc.s
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/transaction/timestamp.cc.s
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/transaction/timestamp.cc.s
.PHONY : src/mica/transaction/timestamp.cc.s

src/mica/util/cityhash/city_mod.o: src/mica/util/cityhash/city_mod.cc.o

.PHONY : src/mica/util/cityhash/city_mod.o

# target to build an object file
src/mica/util/cityhash/city_mod.cc.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/cityhash/city_mod.cc.o
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/cityhash/city_mod.cc.o
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/cityhash/city_mod.cc.o
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/cityhash/city_mod.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/cityhash/city_mod.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/cityhash/city_mod.cc.o
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/cityhash/city_mod.cc.o
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/cityhash/city_mod.cc.o
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/cityhash/city_mod.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/cityhash/city_mod.cc.o
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/cityhash/city_mod.cc.o
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/cityhash/city_mod.cc.o
.PHONY : src/mica/util/cityhash/city_mod.cc.o

src/mica/util/cityhash/city_mod.i: src/mica/util/cityhash/city_mod.cc.i

.PHONY : src/mica/util/cityhash/city_mod.i

# target to preprocess a source file
src/mica/util/cityhash/city_mod.cc.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/cityhash/city_mod.cc.i
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/cityhash/city_mod.cc.i
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/cityhash/city_mod.cc.i
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/cityhash/city_mod.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/cityhash/city_mod.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/cityhash/city_mod.cc.i
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/cityhash/city_mod.cc.i
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/cityhash/city_mod.cc.i
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/cityhash/city_mod.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/cityhash/city_mod.cc.i
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/cityhash/city_mod.cc.i
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/cityhash/city_mod.cc.i
.PHONY : src/mica/util/cityhash/city_mod.cc.i

src/mica/util/cityhash/city_mod.s: src/mica/util/cityhash/city_mod.cc.s

.PHONY : src/mica/util/cityhash/city_mod.s

# target to generate assembly for a file
src/mica/util/cityhash/city_mod.cc.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/cityhash/city_mod.cc.s
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/cityhash/city_mod.cc.s
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/cityhash/city_mod.cc.s
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/cityhash/city_mod.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/cityhash/city_mod.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/cityhash/city_mod.cc.s
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/cityhash/city_mod.cc.s
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/cityhash/city_mod.cc.s
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/cityhash/city_mod.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/cityhash/city_mod.cc.s
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/cityhash/city_mod.cc.s
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/cityhash/city_mod.cc.s
.PHONY : src/mica/util/cityhash/city_mod.cc.s

src/mica/util/config.o: src/mica/util/config.cc.o

.PHONY : src/mica/util/config.o

# target to build an object file
src/mica/util/config.cc.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/config.cc.o
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/config.cc.o
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/config.cc.o
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/config.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/config.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/config.cc.o
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/config.cc.o
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/config.cc.o
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/config.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/config.cc.o
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/config.cc.o
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/config.cc.o
.PHONY : src/mica/util/config.cc.o

src/mica/util/config.i: src/mica/util/config.cc.i

.PHONY : src/mica/util/config.i

# target to preprocess a source file
src/mica/util/config.cc.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/config.cc.i
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/config.cc.i
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/config.cc.i
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/config.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/config.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/config.cc.i
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/config.cc.i
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/config.cc.i
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/config.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/config.cc.i
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/config.cc.i
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/config.cc.i
.PHONY : src/mica/util/config.cc.i

src/mica/util/config.s: src/mica/util/config.cc.s

.PHONY : src/mica/util/config.s

# target to generate assembly for a file
src/mica/util/config.cc.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/config.cc.s
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/config.cc.s
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/config.cc.s
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/config.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/config.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/config.cc.s
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/config.cc.s
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/config.cc.s
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/config.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/config.cc.s
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/config.cc.s
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/config.cc.s
.PHONY : src/mica/util/config.cc.s

src/mica/util/lcore.o: src/mica/util/lcore.cc.o

.PHONY : src/mica/util/lcore.o

# target to build an object file
src/mica/util/lcore.cc.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/lcore.cc.o
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/lcore.cc.o
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/lcore.cc.o
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/lcore.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/lcore.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/lcore.cc.o
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/lcore.cc.o
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/lcore.cc.o
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/lcore.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/lcore.cc.o
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/lcore.cc.o
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/lcore.cc.o
.PHONY : src/mica/util/lcore.cc.o

src/mica/util/lcore.i: src/mica/util/lcore.cc.i

.PHONY : src/mica/util/lcore.i

# target to preprocess a source file
src/mica/util/lcore.cc.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/lcore.cc.i
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/lcore.cc.i
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/lcore.cc.i
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/lcore.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/lcore.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/lcore.cc.i
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/lcore.cc.i
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/lcore.cc.i
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/lcore.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/lcore.cc.i
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/lcore.cc.i
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/lcore.cc.i
.PHONY : src/mica/util/lcore.cc.i

src/mica/util/lcore.s: src/mica/util/lcore.cc.s

.PHONY : src/mica/util/lcore.s

# target to generate assembly for a file
src/mica/util/lcore.cc.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/lcore.cc.s
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/lcore.cc.s
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/lcore.cc.s
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/lcore.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/lcore.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/lcore.cc.s
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/lcore.cc.s
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/lcore.cc.s
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/lcore.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/lcore.cc.s
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/lcore.cc.s
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/lcore.cc.s
.PHONY : src/mica/util/lcore.cc.s

src/mica/util/siphash/siphash24.o: src/mica/util/siphash/siphash24.c.o

.PHONY : src/mica/util/siphash/siphash24.o

# target to build an object file
src/mica/util/siphash/siphash24.c.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/siphash/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/siphash/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/siphash/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/siphash/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/siphash/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/siphash/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/siphash/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/siphash/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/siphash/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/siphash/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/siphash/siphash24.c.o
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/siphash/siphash24.c.o
.PHONY : src/mica/util/siphash/siphash24.c.o

src/mica/util/siphash/siphash24.i: src/mica/util/siphash/siphash24.c.i

.PHONY : src/mica/util/siphash/siphash24.i

# target to preprocess a source file
src/mica/util/siphash/siphash24.c.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/siphash/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/siphash/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/siphash/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/siphash/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/siphash/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/siphash/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/siphash/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/siphash/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/siphash/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/siphash/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/siphash/siphash24.c.i
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/siphash/siphash24.c.i
.PHONY : src/mica/util/siphash/siphash24.c.i

src/mica/util/siphash/siphash24.s: src/mica/util/siphash/siphash24.c.s

.PHONY : src/mica/util/siphash/siphash24.s

# target to generate assembly for a file
src/mica/util/siphash/siphash24.c.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/siphash/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/siphash/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/siphash/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/siphash/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/siphash/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/siphash/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/siphash/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/siphash/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/siphash/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/siphash/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/siphash/siphash24.c.s
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/siphash/siphash24.c.s
.PHONY : src/mica/util/siphash/siphash24.c.s

src/mica/util/stopwatch.o: src/mica/util/stopwatch.cc.o

.PHONY : src/mica/util/stopwatch.o

# target to build an object file
src/mica/util/stopwatch.cc.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/stopwatch.cc.o
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/stopwatch.cc.o
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/stopwatch.cc.o
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/stopwatch.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/stopwatch.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/stopwatch.cc.o
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/stopwatch.cc.o
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/stopwatch.cc.o
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/stopwatch.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/stopwatch.cc.o
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/stopwatch.cc.o
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/stopwatch.cc.o
.PHONY : src/mica/util/stopwatch.cc.o

src/mica/util/stopwatch.i: src/mica/util/stopwatch.cc.i

.PHONY : src/mica/util/stopwatch.i

# target to preprocess a source file
src/mica/util/stopwatch.cc.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/stopwatch.cc.i
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/stopwatch.cc.i
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/stopwatch.cc.i
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/stopwatch.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/stopwatch.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/stopwatch.cc.i
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/stopwatch.cc.i
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/stopwatch.cc.i
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/stopwatch.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/stopwatch.cc.i
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/stopwatch.cc.i
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/stopwatch.cc.i
.PHONY : src/mica/util/stopwatch.cc.i

src/mica/util/stopwatch.s: src/mica/util/stopwatch.cc.s

.PHONY : src/mica/util/stopwatch.s

# target to generate assembly for a file
src/mica/util/stopwatch.cc.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/stopwatch.cc.s
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/stopwatch.cc.s
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/stopwatch.cc.s
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/stopwatch.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/stopwatch.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/stopwatch.cc.s
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/stopwatch.cc.s
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/stopwatch.cc.s
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/stopwatch.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/stopwatch.cc.s
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/stopwatch.cc.s
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/stopwatch.cc.s
.PHONY : src/mica/util/stopwatch.cc.s

src/mica/util/zipf.o: src/mica/util/zipf.cc.o

.PHONY : src/mica/util/zipf.o

# target to build an object file
src/mica/util/zipf.cc.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/zipf.cc.o
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/zipf.cc.o
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/zipf.cc.o
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/zipf.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/zipf.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/zipf.cc.o
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/zipf.cc.o
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/zipf.cc.o
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/zipf.cc.o
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/zipf.cc.o
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/zipf.cc.o
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/zipf.cc.o
.PHONY : src/mica/util/zipf.cc.o

src/mica/util/zipf.i: src/mica/util/zipf.cc.i

.PHONY : src/mica/util/zipf.i

# target to preprocess a source file
src/mica/util/zipf.cc.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/zipf.cc.i
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/zipf.cc.i
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/zipf.cc.i
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/zipf.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/zipf.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/zipf.cc.i
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/zipf.cc.i
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/zipf.cc.i
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/zipf.cc.i
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/zipf.cc.i
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/zipf.cc.i
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/zipf.cc.i
.PHONY : src/mica/util/zipf.cc.i

src/mica/util/zipf.s: src/mica/util/zipf.cc.s

.PHONY : src/mica/util/zipf.s

# target to generate assembly for a file
src/mica/util/zipf.cc.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/mica/util/zipf.cc.s
	$(MAKE) -f CMakeFiles/test_tx.dir/build.make CMakeFiles/test_tx.dir/src/mica/util/zipf.cc.s
	$(MAKE) -f CMakeFiles/test_tx_index.dir/build.make CMakeFiles/test_tx_index.dir/src/mica/util/zipf.cc.s
	$(MAKE) -f CMakeFiles/test_partial_commit.dir/build.make CMakeFiles/test_partial_commit.dir/src/mica/util/zipf.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_detection.dir/build.make CMakeFiles/test_cxl_detection.dir/src/mica/util/zipf.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_slot.dir/build.make CMakeFiles/test_cxl_slot.dir/src/mica/util/zipf.cc.s
	$(MAKE) -f CMakeFiles/test_tsc_sync.dir/build.make CMakeFiles/test_tsc_sync.dir/src/mica/util/zipf.cc.s
	$(MAKE) -f CMakeFiles/test_bwtree_index.dir/build.make CMakeFiles/test_bwtree_index.dir/src/mica/util/zipf.cc.s
	$(MAKE) -f CMakeFiles/test_atomics.dir/build.make CMakeFiles/test_atomics.dir/src/mica/util/zipf.cc.s
	$(MAKE) -f CMakeFiles/test_cxl_row_data.dir/build.make CMakeFiles/test_cxl_row_data.dir/src/mica/util/zipf.cc.s
	$(MAKE) -f CMakeFiles/test_simple_slot_read.dir/build.make CMakeFiles/test_simple_slot_read.dir/src/mica/util/zipf.cc.s
	$(MAKE) -f CMakeFiles/test_commit_slot_access.dir/build.make CMakeFiles/test_commit_slot_access.dir/src/mica/util/zipf.cc.s
.PHONY : src/mica/util/zipf.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... common"
	@echo "... test_tx"
	@echo "... test_tx_index"
	@echo "... test_partial_commit"
	@echo "... test_cxl_detection"
	@echo "... test_cxl_slot"
	@echo "... test_tsc_sync"
	@echo "... test_bwtree_index"
	@echo "... test_atomics"
	@echo "... test_cxl_row_data"
	@echo "... test_simple_slot_read"
	@echo "... test_commit_slot_access"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... src/mica/alloc/hugetlbfs_shm.o"
	@echo "... src/mica/alloc/hugetlbfs_shm.i"
	@echo "... src/mica/alloc/hugetlbfs_shm.s"
	@echo "... src/mica/test/test_atomics.o"
	@echo "... src/mica/test/test_atomics.i"
	@echo "... src/mica/test/test_atomics.s"
	@echo "... src/mica/test/test_bwtree_index.o"
	@echo "... src/mica/test/test_bwtree_index.i"
	@echo "... src/mica/test/test_bwtree_index.s"
	@echo "... src/mica/test/test_commit_slot_access.o"
	@echo "... src/mica/test/test_commit_slot_access.i"
	@echo "... src/mica/test/test_commit_slot_access.s"
	@echo "... src/mica/test/test_cxl_detection.o"
	@echo "... src/mica/test/test_cxl_detection.i"
	@echo "... src/mica/test/test_cxl_detection.s"
	@echo "... src/mica/test/test_cxl_row_data.o"
	@echo "... src/mica/test/test_cxl_row_data.i"
	@echo "... src/mica/test/test_cxl_row_data.s"
	@echo "... src/mica/test/test_cxl_slot.o"
	@echo "... src/mica/test/test_cxl_slot.i"
	@echo "... src/mica/test/test_cxl_slot.s"
	@echo "... src/mica/test/test_partial_commit.o"
	@echo "... src/mica/test/test_partial_commit.i"
	@echo "... src/mica/test/test_partial_commit.s"
	@echo "... src/mica/test/test_simple_slot_read.o"
	@echo "... src/mica/test/test_simple_slot_read.i"
	@echo "... src/mica/test/test_simple_slot_read.s"
	@echo "... src/mica/test/test_tsc_sync.o"
	@echo "... src/mica/test/test_tsc_sync.i"
	@echo "... src/mica/test/test_tsc_sync.s"
	@echo "... src/mica/test/test_tx.o"
	@echo "... src/mica/test/test_tx.i"
	@echo "... src/mica/test/test_tx.s"
	@echo "... src/mica/test/test_tx_index.o"
	@echo "... src/mica/test/test_tx_index.i"
	@echo "... src/mica/test/test_tx_index.s"
	@echo "... src/mica/transaction/timestamp.o"
	@echo "... src/mica/transaction/timestamp.i"
	@echo "... src/mica/transaction/timestamp.s"
	@echo "... src/mica/util/cityhash/city_mod.o"
	@echo "... src/mica/util/cityhash/city_mod.i"
	@echo "... src/mica/util/cityhash/city_mod.s"
	@echo "... src/mica/util/config.o"
	@echo "... src/mica/util/config.i"
	@echo "... src/mica/util/config.s"
	@echo "... src/mica/util/lcore.o"
	@echo "... src/mica/util/lcore.i"
	@echo "... src/mica/util/lcore.s"
	@echo "... src/mica/util/siphash/siphash24.o"
	@echo "... src/mica/util/siphash/siphash24.i"
	@echo "... src/mica/util/siphash/siphash24.s"
	@echo "... src/mica/util/stopwatch.o"
	@echo "... src/mica/util/stopwatch.i"
	@echo "... src/mica/util/stopwatch.s"
	@echo "... src/mica/util/zipf.o"
	@echo "... src/mica/util/zipf.i"
	@echo "... src/mica/util/zipf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

